# --- /etc/dnsmasq.conf ---

# ログ出力
#	デバッグ用・本番稼働でログを減らしたい場合はコメントアウト可）
log-dhcp

# 1. DNS機能を無効化
port=0

# 2. バインド設定
#	全インターフェースで受信、ループバックのみ除外
except-interface=lo

# 3. DHCP Proxy モード設定
#	ネットワーク 192.168.17.0/24 のクライアントに対して、DHCPリクエストを中継する
dhcp-range=192.168.17.0,proxy,255.255.255.0

# 4. UEFI クライアント識別
# 	7 = EFI x86-64, 9 = EFI BC (x86-64)
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efi64,option:client-arch,9

# 5. PXE ブート指定
#	PXEブートメニュー および ブートローダーの指定
#	ブートローダーの取得先に、TFTPサーバーのIPアドレスを指定
pxe-service=tag:efi64,X86-64_EFI,"Install AlmaLinux 9",BOOTX64.EFI
dhcp-boot=tag:efi64,BOOTX64.EFI,192.168.17.131

# 6. TFTP サーバー設定
#	TFTPサーバーを有効化し、ブートローダーの取得先ディレクトリを指定
enable-tftp
tftp-root=/var/lib/tftpboot
